config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "user/registrations", sessions: "user/sessions", confirmations: "user/confirmations", passwords: "user/passwords", :omniauth_callbacks => "user/omniauth_callbacks"}
     
  get '/dashboard' => 'users#dashboard', as: "dashboard"

  root 'users#direct_root'

  scope :users do
    get ':username' => 'users#profile',:constraints => { :username => /[^\/]+/ }, as: "show_profile"
  end

  resources :users do
    get :autocomplete_tag_name, :on => :collection
  end

  scope :projects do
    get '/taken' => 'projects#taken' , as: "taken_projects"
    get '/bidded' => 'projects#bidded', as: "bidded_projects"
    get '/completed' => 'projects#completed', as: "completed_projects"
    get '/posted' => 'projects#posted', as: "posted_projects"
  end

  resources :projects do
      get :autocomplete_tag_name, :on => :collection
  end

  get "*path" => redirect('/')
  
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :poster, class_name: 'User'
	belongs_to :employee, class_name: 'User'
	belongs_to :finisher, class_name: 'User'
	has_and_belongs_to_many :bidders, class_name: 'User', join_table: "bidders_projects",foreign_key: "bidded_project_id", association_foreign_key: "bidder_id"
	has_and_belongs_to_many :categories, class_name: 'Category', join_table: "categories_projects", foreign_key: "project_id", association_foreign_key: "category_id"
	validates_presence_of :budget , :description , :title , :time , :poster_id
	validates_length_of :description, minimum: 0, maximum: 400


	acts_as_taggable_on :tags
	acts_as_ordered_taggable_on :tags
	scope :by_join_date, ->{
	    order("created_at DESC")
  	}

  	def tag_list
  		owner_tags_on(self.poster,:tags)
  	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  autocomplete :tag, :name, :class_name => 'ActsAsTaggableOn::Tag' 

  before_action :set_project , only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , only: [:new, :edit, :create, :update, :posted, :taken, :bidded, :completed]
  before_action :check_authority , only: [:update, :edit, :destroy]
  # GET /projects
  # GET /projects.json
  def index

    if params[:tag]
    @projects = Project.tagged_with(params[:tag])
  else
    @projects = Project.all
  end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  def setter project_params
    newparams = Hash.new()
    newparams = {:title => project_params[:title],:description => project_params[:description], :budget => project_params[:budget], :time => project_params[:time]}
  end

  # POST /projects
  # POST /projects.json
  def create
    newparams = setter(project_params)
    @project = Project.new(newparams)
    @project.poster = current_user
    @project.poster.tag(@project, :with => project_params[:tag_list] , :on => :tags)
    copy_categories
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    newparams = setter(project_params)
    respond_to do |format|
      if @project.update(newparams)
        @project.poster.tag(@project, :with => project_params[:tag_list] , :on => :tags)
        copy_categories
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def taken
    @projects = current_user.taken_projects
  end

  def completed
    @projects = current_user.completed_projects
  end

  def bidded
    @projects = current_user.bidded_projects
  end

  def posted
    @projects = current_user.posted_projects
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :tag_list, :budget, :time,:tag, { tag_ids: [] }, :tag_ids, :categories)
    end

    def check_authority
      if current_user == @project.poster
        true
      else
        redirect_to '/projects' , alert: "Unauthorized to make any change"
        return
      end
    end

    def copy_categories
      @project.categories.delete_all
      params[:project][:categories].each do |id|
        if (not Category.find_by_id(id).nil?) and (@project.categories.find_by_id(id).nil?)
          @project.categories << Category.find(id)
        end
      end

    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def set_value project
		if project.tag_list.count == 0
			""
		else
			array= Array.new
			project.tag_list.each do |tag|
				temp = "#{tag}, "
				array << temp
			end
			array
		end
	end
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

    <div class="field">
      <%= f.label :Category %><br/><br/>
      <%= f.collection_check_boxes(:categories, Category.all, :id,:name, {:prompt=>true}) %>
    </div>
    <br/>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :skills %><br>
     <%= f.autocomplete_field :tag_list, autocomplete_tag_name_projects_path, :"data-delimiter" => ', ', :value =>set_value(@project)%>
  </div>

  <div class="field">
    <%= f.label :budget %><br>
    <%= f.text_field :budget %>
  </div>

  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.text_field :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_tag.html.erb
<div class="tag">
<%= tag %>
</div>

app/views/projects/bidded.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Budget</th>
    <th>Time</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.budget %></td>
        <td><%= project.time %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/completed.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Budget</th>
    <th>Time</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.budget %></td>
        <td><%= project.time %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Skills</th>
      <th>Budget</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.owner_tags_on(project.poster,:tags).map{ |t| t}.join(', ') %></td>
        <td><%= project.budget %></td>
        <td><%= project.time %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/posted.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Budget</th>
    <th>Time</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.budget %></td>
        <td><%= project.time %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/show.html.erb
<p id="notice"><%#= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Category:</strong><br/>
  <% @project.categories.each do |c| %>
  <%= c.name %><br/>
  <%end%>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Skills:</strong>
  <% @project.owner_tags_on(@project.poster,:tags).each do |tag| %>
  <%= render 'tag' , :tag => tag %>
  <% end %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @project.budget %>
</p>

<p>
  <strong>Time:</strong>
  <%= @project.time %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/taken.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Budget</th>
    <th>Time</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.budget %></td>
        <td><%= project.time %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>