config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "user/registrations", sessions: "user/sessions", confirmations: "user/confirmations", passwords: "user/passwords", :omniauth_callbacks => "user/omniauth_callbacks"}
     
  get '/dashboard' => 'users#dashboard', as: "dashboard"

  root 'users#direct_root'

  scope :users do
    get ':username' => 'users#profile',:constraints => { :username => /[^\/]+/ }, as: "show_profile"
  end

  resources :users do
    get :autocomplete_tag_name, :on => :collection
  end

  scope :projects do
    get '/taken' => 'projects#taken' , as: "taken_projects"
    get '/bidded' => 'projects#bidded', as: "bidded_projects"
    get '/completed' => 'projects#completed', as: "completed_projects"
    get '/posted' => 'projects#posted', as: "posted_projects"
  end

  resources :projects do
      get :autocomplete_tag_name, :on => :collection
  end

  get "*path" => redirect('/')
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", "custom-theme/jquery-ui-1.8.9.custom" %>
  <%= javascript_include_tag :defaults, "jquery-ui-#.#.#.custom.min", "autocomplete-rails" %>
  <!-- Compiled and minified CSS  except version 0.97.6 of materialize, no lib is compatible
  because below this version, the side bar will not work and above this version the drop down button
  will not work on hovering-->
  <link rel="stylesheet" href="http://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">

  <title>Portal</title>
</head>
<body>

<% if not notice.nil? or not alert.nil? %>
    <div id="alert"><p id="notice" style="color : orange ;  "  ><%=notice %></p>
      <p id="alert" style=" color : orange ; "><%=alert %></p>
    </div>
<% end %>

<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper container">
      <a href="/" class="brand-logo">Portal</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul id="head_nav" class="right hide-on-med-and-down">
        <% if user_signed_in? %>
            <li>
              <div class='dropdown-button btn' data-activates='dropdown1' style="max-width : 180px;">Hi <%=current_user.first_name %></div>
              <!-- Dropdown Structure -->
              <ul id='dropdown1' class='dropdown-content'>
                <li><%= link_to "Profile", show_profile_path(username: current_user.username) %></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path%></li>
                <li class="divider"></li>
                <li><%= link_to "SignOut", destroy_user_session_path, method: "Delete"%></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "LogIn", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end%>
        </li>
        <li>
          <nav>
            <div class="nav-wrapper">
              <form action="/questions/search" method="get">
                <div class="input-field">
                  <input id="search" name="query" type="search" required>
                  <label for="search"><i class="material-icons">search</i></label>
                  <i class="material-icons">close</i>
                </div>
              </form>
            </div>
          </nav>
        </li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <% if user_signed_in? %>
            <li style="color: black;">
              <%= link_to "Hello "+current_user.first_name, '#'%>
            </li>
            <li style="color: black;">
              <%= link_to "Profile", show_profile_path(username: current_user.username) %>
            </li>
            <li style="color: black;">
              <%= link_to "Edit Profile" , edit_user_registration_path%>
            </li>
            <li>
              <%= link_to "SignOut", destroy_user_session_path, method: "Delete"%>
            </li>
        <% else %>
            <li>
              <%= link_to "LogIn", new_user_session_path %>
            </li>
            <li>
              <%= link_to "Sign Up", new_user_registration_path %>
            </li>
        <% end %>
        <li>
          <nav>
            <div class="nav-wrapper">
              <form action="/questions/search" method="get">
                <div class="input-field">
                  <input id="search" name="query" type="search" required>
                  <label for="search"><i class="material-icons">search</i></label>
                  <i class="material-icons">close</i>
                </div>
              </form>
            </div>
          </nav>
        </li>
      </ul>
    </div>
  </nav>
</div>



<div class="container">
  <%= yield %>
</div>



<div class="footer" style="height: 200px;">
</div>

<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js" defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js" defer></script>
<script>
    $(document).on('ready page:load', function () {
        $('#product_tag_ids').chosen({
            allow_single_deselect: true,
            width: '100%'
        })
    });

    $(document).ready(function(){
        $(".button-collapse").sideNav();
        $("#alert").delay(2500).slideUp('slow');
        $('.dropdown-button').dropdown({
                inDuration: 400,
                outDuration: 600,
                constrain_width: true, // Does not change width of dropdown to that of the activator
                hover: true, // Activate on hover
                gutter: 0, // Spacing from edge
                belowOrigin: true, // Displays dropdown below the button
                alignment: 'left' // Displays dropdown with edge aligned to the left of button
            }
        );
    })
    <% if not pop.nil? %>
    alert("<%= pop %>")
    <%end%>
</script>
</body>
</html>